package com.databuilder.com.br.abcdata.services;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.databuilder.com.br.abcdata.entity.Disciplina;
import com.databuilder.com.br.abcdata.entity.Estudante;
import com.databuilder.com.br.abcdata.entity.Login;
import com.databuilder.com.br.abcdata.entity.Servidor;
import com.databuilder.com.br.abcdata.entity.UnidadeEducacional;
import com.databuilder.com.br.abcdata.entity.enums.NivelDeAcesso;
import com.databuilder.com.br.abcdata.entity.enums.SituacaoEntrega;
import com.databuilder.com.br.abcdata.entity.enums.SituacaoEstudante;
import com.databuilder.com.br.abcdata.entity.enums.StatusLogin;
import com.databuilder.com.br.abcdata.entity.enums.TipoEtnia;
import com.databuilder.com.br.abcdata.entity.enums.TipoGenero;
import com.databuilder.com.br.abcdata.entity.enums.TipoServidor;
import com.databuilder.com.br.abcdata.repositories.DisciplinaRepository;
import com.databuilder.com.br.abcdata.repositories.EstudanteRepository;
import com.databuilder.com.br.abcdata.repositories.LoginRepository;
import com.databuilder.com.br.abcdata.repositories.ServidorRepository;
import com.databuilder.com.br.abcdata.repositories.UnidadeEducacionalRepository;

@Service
public class DBService {

	@Autowired
	private PasswordEncoder pe;

	@Autowired
	private LoginRepository loginRepository;

	@Autowired
	private UnidadeEducacionalRepository unidadeEducacionalRepository;

	@Autowired
	private ServidorRepository servidorRepository;


	@Autowired
	private DisciplinaRepository disciplinaRepository;

	@Autowired
	private EstudanteRepository estudanteRepository;

	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
	SimpleDateFormat sdfs = new SimpleDateFormat("dd/MM/yyyy");

	public void instantiateTestDatabase() throws ParseException {

		Login log1 = new Login(null, "diretor", "ADEROGILDO DA SILVA", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.DIRETOR_UN_EDUCACIONAL);
		Login log2 = new Login(null, "coordenador", "MARIA DA SILVA", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.COORDENADOR_UN_EDUCACIONAL);
		Login log3 = new Login(null, "teste@teste2.com.br", "JORGE NAILTON", pe.encode("1"), new Date(System.currentTimeMillis()), StatusLogin.BLOQUEADO, 0, NivelDeAcesso.PROFESSOR);
		Login log4 = new Login(null, "teste@teste3.com.br", "LEANDRO LIANDERSON", pe.encode("1"), new Date(), StatusLogin.INATIVO, 0, NivelDeAcesso.PROFESSOR);
		Login log5 = new Login(null, "admin", "WENDELL CLIVE SANTOS DE LIRA", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.ADMIN);
		Login log6 = new Login(null, "teste@teste4.com.br", "DECAMERON RODRIGUES ALVES", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.PROFESSOR);
		Login log7 = new Login(null, "teste@teste5.com.br", "CHARITAS HONORATO NUNES", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.PROFESSOR);
		Login log8 = new Login(null, "secretaria", "LUCICLELSON RAMIRES", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.SECRETARIA_UN_EDUCACIONAL);
		Login log9 = new Login(null, "professor", "MARIA APARECIDA XUXU", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.PROFESSOR);
		Login log10 = new Login(null, "gestorgeral", "NICACIO PERILO DA SILVA", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.GESTOR_GERAL);
		Login log11 = new Login(null, "gerentenucleo", "JOAO JOSE DA SILVAS", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.GERENTE_NUCLEO);
		Login log12 = new Login(null, "estudante", "CORINA SANTOS DA COSTA", pe.encode("1"), new Date(), StatusLogin.ATIVO, 0, NivelDeAcesso.ESTUDANTE);

		loginRepository
				.saveAll(Arrays.asList(log1, log2, log3, log4, log5, log6, log7, log8, log9, log10, log11, log12));

		Servidor ser1 = new Servidor(null, 2018001, log1.getNomeUsuario(),"01962636461", TipoGenero.MASCULINO, TipoEtnia.BRANCA, "BRASILEIRA", TipoServidor.ADMINISTRATIVO);
		Servidor ser2 = new Servidor(null, 2018002, log2.getNomeUsuario(),"12345678944", TipoGenero.FEMININO, TipoEtnia.BRANCA, "BRASILEIRA", TipoServidor.PEDAGOGICO);
		Servidor ser3 = new Servidor(null, 2018003, log3.getNomeUsuario(),"55544466677", TipoGenero.MASCULINO, TipoEtnia.NEGRA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser4 = new Servidor(null, 2018004, log4.getNomeUsuario(),"99988855532", TipoGenero.MASCULINO, TipoEtnia.PARDA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser5 = new Servidor(null, 2018005, log5.getNomeUsuario(),"32165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser6 = new Servidor(null, 2018006, log6.getNomeUsuario(),"42165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser7 = new Servidor(null, 2018007, log7.getNomeUsuario(),"52165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser8 = new Servidor(null, 2018008, log8.getNomeUsuario(),"62165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser9 = new Servidor(null, 2018009, log9.getNomeUsuario(),"72165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser10 = new Servidor(null, 2018010, log10.getNomeUsuario(),"82165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);
		Servidor ser11 = new Servidor(null, 2018011, log11.getNomeUsuario(),"92165498799", TipoGenero.MASCULINO, TipoEtnia.AMARELA, "BRASILEIRA", TipoServidor.PROFESSOR);

		UnidadeEducacional unedu1 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "123456", "EMEF JOAO DORIA DA SILVA", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu2 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "459877", "EMEM II ARGENTINA PEREIRA GOMES", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu3 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "984654", "EMEF JOAO GOMES DE SA", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu4 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "354791", "EMEF ARLINDA MARQUES", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu5 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "194964", "EMEF TEOTONIO VILELA", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu6 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "654749", "EMEF CRISTIAN LOBATO", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu7 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "321478", "EMEF ORLANDO DO MONTE", 1,  1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);
		UnidadeEducacional unedu8 = new UnidadeEducacional(null, new Date(System.currentTimeMillis()), "987412", "EMEM JOSE LINS DO REGO", 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1);

		ser1.getUnidadesEducacionais().addAll(Arrays.asList(unedu1, unedu4));
		ser2.getUnidadesEducacionais().addAll(Arrays.asList(unedu2));
		ser3.getUnidadesEducacionais().addAll(Arrays.asList(unedu1, unedu3));
		ser4.getUnidadesEducacionais().addAll(Arrays.asList(unedu4));
		ser5.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));
		ser6.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));
		ser7.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));
		ser8.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));
		ser9.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));
		ser10.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));
		ser11.getUnidadesEducacionais().addAll(Arrays.asList(unedu3, unedu5));

		unedu1.getServidores().addAll(Arrays.asList(ser1, ser3));
		unedu2.getServidores().addAll(Arrays.asList(ser2));
		unedu3.getServidores().addAll(Arrays.asList(ser3, ser5));
		unedu4.getServidores().addAll(Arrays.asList(ser4, ser1));
		unedu5.getServidores().addAll(Arrays.asList(ser5));

		servidorRepository.saveAll(Arrays.asList(ser1, ser2, ser3, ser4, ser5, ser6, ser7, ser8, ser9, ser10, ser11));

		unidadeEducacionalRepository
				.saveAll(Arrays.asList(unedu1, unedu2, unedu3, unedu4, unedu5, unedu6, unedu7, unedu8));

		Disciplina d1 = new Disciplina(null, "PORTUGUES", 60);
		Disciplina d2 = new Disciplina(null, "GEOGRAFIA", 40);
		Disciplina d3 = new Disciplina(null, "MATEMATICA", 60);
		Disciplina d4 = new Disciplina(null, "HISTORIA", 40);
		Disciplina d5 = new Disciplina(null, "CIENCIAS", 40);
		Disciplina d6 = new Disciplina(null, "FISICA", 40);
		Disciplina d7 = new Disciplina(null, "QUIMICA", 40);
		Disciplina d8 = new Disciplina(null, "FILOSOFIA", 40);
		Disciplina d9 = new Disciplina(null, "RELIGIAO", 40);
		Disciplina d10 = new Disciplina(null, "BIOLOGIA", 40);
		Disciplina d11 = new Disciplina(null, "GENETICA", 40);
		Disciplina d12 = new Disciplina(null, "INFORMATICA", 30);
		Disciplina d13 = new Disciplina(null, "ROBOTICA", 30);

		disciplinaRepository.saveAll(Arrays.asList(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13));

		Estudante estudante1= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000001, "ADRYANNE PORTILHO CARNEIRO MENDES", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", log12, null,null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);	
		Estudante estudante2= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000002, "ALESSANDRA MENDES MONTEIRO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante3= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000003, "ALEX ALVES BARBOSA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante4= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000004, "ALINE LIMA CAMPELO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null,"JOAO DA SILVA","joão@dasilva.com.br","999546546", SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante6= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000006, "ANDRÉ LUIS GONZALES AMORIS", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null,"JOAO DA SILVA","joão@dasilva.com.br","999546546", SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante5= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000005, "ÁLISTER ALVES MOREIRA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante7= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000007, "ANTONIO MANOEL DA SILVEIRA JUNIOR", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante8= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000008, "AQUILES DE ALMEIDA JUNIOR", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante9= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000009, "BRUNO ENRICO GONÇALVES DOS SANTOS", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante10= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000010, "CAMILO LEANDRO SALES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null,"JOAO DA SILVA","joão@dasilva.com.br","999546546", SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante11= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000011, "CÁSSIO HENRIQUE GOMES DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante12= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000012, "CIRO HENRIQUES ÁSPERA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante13= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000013, "CLODOMIR GHIZONI", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante14= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000014, "CRISTIAN DA LUZ VIDAL", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante15= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000015, "DANIEL OLIVEIRA NUNES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante16= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000016, "DANIELI BONATO HALOTEN", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante17= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000017, "DANILA CRISTINA MAKIHAMA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante18= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000018, "DANILO DA SILVA OLIVEIRA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante19= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000019, "DENISE MOREIRA DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante20= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000020, "DIOGO LUIZ LEITE DE ARAUJO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante21= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000021, "DIOGO RODRIGO CECCON", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante22= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000022, "EDMAIONS DA SILVA CARVALHO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante23= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000023, "EDUARDO DA SILVA SARDÃO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante24= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000024, "ELENICE VIEIRA DE ANDRADE", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante25= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000025, "ELKA JANAÍNA DOS SANTOS E SILVA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante26= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000026, "ELVYS WANDERLEY DE MELO SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante27= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000027, "EVANYL TAPAJOS DE LIMA MATTOS", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante28= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000028, "FABIO SIDNEI RODRIGUES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante29= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000029, "GILBERTO SEBASTIÃO ALVES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante30= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000030, "GILNEI FERRAZ", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante31= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000031, "GLEYDSON MATEUS DE OLIVEIRA PEIXOTO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante32= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000032, "GORETI HENSEL CARDOSO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante33= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000033, "GUILHERME FREITAS GONÇALVES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante34= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000034, "GUSTAVO SILVA DE ALMEIDA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante35= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000035, "JESUS PEREIRA DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante36= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000036, "JHON JACKSON MOCCELINI", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante37= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000037, "JOSE CARLOS ALMEIDA DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante38= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000038, "JOSE FERNANDO MARCENA SOUZA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante39= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000039, "JOSÉ MARCOS DE CARVALHO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante40= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000040, "JOSE MICAEL BISPO RODRIGUES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante41= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000041, "JOSEMBERGUE DOS SANTOS SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante42= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000042, "JOSEMIAS NASCIMENTO DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante43= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000043, "JOSIANE BATISTA ROCHA MENEZES", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante44= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000044, "JUCIMARA DAS MERCÊS NASCIMENTO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante45= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000045, "JUNIOR CESAR VERA DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante46= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000046, "KARLA SILVA DE SÁ LOPES", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante47= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000047, "KAROLINE DA SILVA CASTRO FERRETTI", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante48= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000048, "KENNEDY CARLOS FERREIRA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante49= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000049, "KIM DEMIAN FIGUEIREDO MODESTO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante50= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000050, "LAURA DA CONCEIÇÃO LUZ SANTOS", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante51= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000051, "LEILA DOS SANTOS PEREIRA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante52= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000052, "LEONARDO CARVALHO MARTINS SALES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante53= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000053, "LEONARDO MARCELO ALVES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante54= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000054, "LEONARDO MARI DE CASTRO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante55= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000055, "LICIANE AGDA CRUZ FIGUEIRA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante56= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000056, "LUAN LOPES DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante57= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000057, "LUCAS ALVES ALBUQUERQUE", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante58= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000058, "LUCAS ARAUJO VASQUES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante59= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000059, "LUCAS COSTA CAIRES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante60= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000060, "LUCAS LISBOA RODRIGUES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante61= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000061, "LUCAS VEGINI", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante62= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000062, "LUIZ CARLOS DE SOUZA FILHO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante63= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000063, "LUIZ DOS SANTOS SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante64= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000064, "MARCIO LUIZ SCHNEEDORF NOVI", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante65= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000065, "MARIAN DE SOUZA CALDAS", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante66= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000066, "MARIANA MARCELE DE ANDRADE FERREIRA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante67= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000067, "MARIANA PEREIRA TORQUATO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante68= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000068, "MAYRLA RODRIGUES LOPES", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante69= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000069, "NORBERTO REIS AMATNECKS FILHO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante70= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000070, "PAULA LEONEL RIBEIRO NETTO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante71= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000071, "PEDRO HENRIQUE CARVALHO BARBOSA COSTA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante72= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000072, "RAFAELA FERREIRA LIMA FALCAO MENESES", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante73= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000073, "REINALDO CESAR FERREIRA NEVES", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante74= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000074, "RENIVALDO DE SOUSA SANTANA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante75= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000075, "RICARDO GONÇALVES DO AMARAL MARTIN", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante76= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000076, "RICARDO LIS", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante77= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000077, "RICHARD BRUNO FERREIRA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante78= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000078, "RINALDO CELESTINO DOS REIS", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante79= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000079, "ROBERTO GOMES DA SILVA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante80= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000080, "RODRIGO DOS SANTOS PESSOA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante81= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000081, "ROGÉRIO DOS SANTOS FONTENELE", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante82= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000082, "ROMUALDO JOÃO MICHELS NETO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante83= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000083, "ROSELI SILVA COSTA HIJO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante84= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000084, "ROSELINE DE PAULA MILAGRES", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante85= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000085, "SANDRA MARIA GOMES DE SOUSA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null,"JOAO DA SILVA","joão@dasilva.com.br","999546546", SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante86= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000086, "SANDRA MARIA MONTEIRO DA CONCEIÇÃO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null,"JOAO DA SILVA","joão@dasilva.com.br","999546546", SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante87= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000087, "SÍLVIA MARIA BARROS", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante88= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000088, "STENIO QUEIROGA DE ALENCAR", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante89= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000089, "SUELLEN DE PAULA CASTELO BRANCO", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null,"JOAO DA SILVA","joão@dasilva.com.br","999546546", SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante90= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000090, "THALES BRUNO DE AGUIAR", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante91= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000091, "THIAGO ARAÚJO PEREIRA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante92= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000092, "THIAGO TOSCHI GAROFANO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante93= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000093, "VILMAR SOARES DO NASCIMENTO", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.BRANCA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante94= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000094, "VINÍCIUS TINOCO VAZ ALMEIDA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante95= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000095, "VIVIANE SOSTIZZO MAGOGA", sdfs.parse("01/02/2010"), TipoGenero.FEMININO, TipoEtnia.PARDA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante96= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000096, "WALFRIDO JOSE DE CAMPOS", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante97= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000097, "WILSON CHINEN", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		Estudante estudante98= new Estudante(null, new Date(System.currentTimeMillis()), new Date(System.currentTimeMillis()), 2019000098, "YURI RAONI SPINDOLA CORREIA", sdfs.parse("01/02/2010"), TipoGenero.MASCULINO, TipoEtnia.NEGRA, "Brasileira", null, null, null, "JOAO DA SILVA","joão@dasilva.com.br","999546546",SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEntrega.ENTREGUE, SituacaoEstudante.ATIVO);
		
		estudanteRepository.saveAll(Arrays.asList(estudante1,	estudante2,	estudante3,	estudante4,	estudante5,	estudante6,	estudante7,	estudante8,	estudante9,	estudante10,	estudante11,	estudante12,	estudante13,	estudante14,	estudante15,	estudante16,	estudante17,	estudante18,	estudante19,	estudante20,	estudante21,	estudante22,	estudante23,	estudante24,	estudante25,	estudante26,	estudante27,	estudante28,	estudante29,	estudante30,	estudante31,	estudante32,	estudante33,	estudante34,	estudante35,	estudante36,	estudante37,	estudante38,	estudante39,	estudante40,	estudante41,	estudante42,	estudante43,	estudante44,	estudante45,	estudante46,	estudante47,	estudante48,	estudante49,	estudante50,
				estudante51,	estudante52,	estudante53,	estudante54,	estudante55,	estudante56,	estudante57,	estudante58,	estudante59,	estudante60,	estudante61,	estudante62,	estudante63,	estudante64,	estudante65,	estudante66,	estudante67,	estudante68,	estudante69,	estudante70,	estudante71,	estudante72,	estudante73,	estudante74,	estudante75,	estudante76,	estudante77,	estudante78,	estudante79,	estudante80,	estudante81,	estudante82,	estudante83,	estudante84,	estudante85,	estudante86,	estudante87,	estudante88,	estudante89,	estudante90,	estudante91,	estudante92,	estudante93,	estudante94,	estudante95,	estudante96,	estudante97,	estudante98));
		
	}
}
